import 'dotenv/config';
import express from 'express';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import cookieParser from 'cookie-parser';
import multer from 'multer';
import argon2 from 'argon2';
import pg from 'pg';
import {randomUUID} from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const {Pool}=pg;
const __dirname=path.dirname(fileURLToPath(import.meta.url));
const app=express();
const pool=new Pool({connectionString:process.env.DATABASE_URL});
const uploadDir=path.join(__dirname,'uploads'); fs.mkdirSync(uploadDir,{recursive:true});
const upload=multer({dest:uploadDir,limits:{fileSize:8*1024*1024},fileFilter:(r,f,cb)=>cb(null,/^image\/(jpeg|png|webp|heic|heif)$/.test(f.mimetype))});
app.use(helmet({crossOriginResourcePolicy:{policy:'same-site'}}));
app.use(express.json({limit:'1mb'})); app.use(cookieParser());
app.use(express.urlencoded({extended:false}));
app.use(rateLimit({windowMs:60_000,max:180,standardHeaders:true,legacyHeaders:false}));
app.use(express.static(__dirname,{index:'daftar.html',dotfiles:'deny'}));
const days=n=>n*24*60*60*1000;
async function q(text,params=[]){return pool.query(text,params)}
async function audit(userId,action,meta={}){await q('INSERT INTO audit_logs(user_id,action,meta) VALUES($1,$2,$3)',[userId,action,JSON.stringify(meta)])}
async function auth(req,res,next){try{const sid=req.cookies.daftar_session;if(!sid)return res.status(401).json({error:'AUTH_REQUIRED'});const r=await q('SELECT u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.id=$1 AND s.expires_at>now()',[sid]);if(!r.rowCount)return res.status(401).json({error:'AUTH_REQUIRED'});req.user=r.rows[0];next()}catch(e){next(e)}}
function safeUser(u){return {id:u.id,username:u.username,role:u.role,trialUntil:new Date(u.trial_until).getTime(),subscriptionUntil:new Date(u.subscription_until).getTime(),plan:u.plan,profile:u.profile||{}}}
app.get('/api/config',(_,res)=>res.json({pay:{card:process.env.PAYMENT_CARD||'',holder:process.env.PAYMENT_HOLDER||''},plans:{monthly:{price:99000,label:'1 oy'}}}));
app.post('/api/auth/register',async(req,res,next)=>{try{const username=String(req.body.username||'').trim().toLowerCase();const password=String(req.body.password||'');if(!/^[a-z0-9_.]{3,40}$/.test(username)||password.length<8)return res.status(400).json({error:'INVALID_INPUT'});const exists=await q('SELECT 1 FROM users WHERE username=$1',[username]);if(exists.rowCount)return res.status(409).json({error:'USERNAME_EXISTS'});const hash=await argon2.hash(password,{type:argon2.argon2id});const id=randomUUID();const trial=new Date(Date.now()+days(Number(process.env.TRIAL_DAYS||7)));await q('INSERT INTO users(id,username,password_hash,trial_until,profile,state) VALUES($1,$2,$3,$4,$5,$6)',[id,username,hash,trial,JSON.stringify({name:'',avatar:''}),JSON.stringify({entries:[],shops:[]})]);await createDefaultShop(id);const user=(await q('SELECT * FROM users WHERE id=$1',[id])).rows[0];await createSession(req,res,id);await audit(id,'register');res.status(201).json({user:safeUser(user)})}catch(e){next(e)}});
app.post('/api/auth/login',async(req,res,next)=>{try{const username=String(req.body.username||'').trim().toLowerCase();const r=await q('SELECT * FROM users WHERE username=$1',[username]);if(!r.rowCount||!(await argon2.verify(r.rows[0].password_hash,String(req.body.password||''))))return res.status(401).json({error:'INVALID_LOGIN'});await createSession(req,res,r.rows[0].id);await audit(r.rows[0].id,'login');res.json({user:safeUser(r.rows[0])})}catch(e){next(e)}});
app.get('/api/auth/me',auth,(req,res)=>res.json({user:safeUser(req.user)}));
app.post('/api/auth/logout',async(req,res)=>{if(req.cookies.daftar_session)await q('DELETE FROM sessions WHERE id=$1',[req.cookies.daftar_session]);res.clearCookie('daftar_session');res.json({ok:true})});
async function createSession(req,res,userId){const id=randomUUID()+randomUUID();await q('INSERT INTO sessions(id,user_id,expires_at) VALUES($1,$2,now()+($3 || \' days\')::interval)',[id,userId,String(Number(process.env.SESSION_DAYS||30))]);res.cookie('daftar_session',id,{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:days(Number(process.env.SESSION_DAYS||30))});}
async function createDefaultShop(userId){const s=await q('SELECT id FROM shops WHERE user_id=$1 LIMIT 1',[userId]);if(!s.rowCount){const id=randomUUID();await q('INSERT INTO shops(id,user_id,name) VALUES($1,$2,$3)',[id,userId,'Asosiy do\'kon']);return id}return s.rows[0].id}
app.get('/api/state',auth,async(req,res,next)=>{try{const shops=await q('SELECT id,name FROM shops WHERE user_id=$1 ORDER BY created_at',[req.user.id]);const st=req.user.state||{};res.json({entries:Array.isArray(st.entries)?st.entries:[],shops:shops.rows,profile:req.user.profile||{}})}catch(e){next(e)}});
app.put('/api/state',auth,async(req,res,next)=>{try{const state={entries:Array.isArray(req.body.entries)?req.body.entries:[],shops:Array.isArray(req.body.shops)?req.body.shops:[],profile:req.body.profile||{}};await q('UPDATE users SET state=$1,profile=$2 WHERE id=$3',[JSON.stringify(state),JSON.stringify(state.profile),req.user.id]);await audit(req.user.id,'state_update');res.json({ok:true})}catch(e){next(e)}});
app.get('/api/products',auth,async(req,res,next)=>{try{const r=await q('SELECT id,name,sku,sale_price as "salePrice",cost_price as "costPrice",stock_qty as "stockQty",min_stock as "minStock",shop_id as shop FROM products WHERE user_id=$1 ORDER BY created_at DESC',[req.user.id]);res.json(r.rows)}catch(e){next(e)}});
app.post('/api/products',auth,async(req,res,next)=>{try{const b=req.body;const id=randomUUID();let shop=b.shop;if(!shop)shop=await createDefaultShop(req.user.id);const r=await q('INSERT INTO products(id,user_id,shop_id,name,sku,sale_price,cost_price,stock_qty,min_stock) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id',[id,req.user.id,shop,String(b.name||'').trim(),b.sku||null,Number(b.salePrice)||0,Number(b.costPrice)||0,Number(b.stockQty)||0,Number(b.minStock)||0]);await audit(req.user.id,'product_create',{id});res.status(201).json(r.rows[0])}catch(e){next(e)}});
app.get('/api/customers',auth,async(req,res,next)=>{try{const r=await q('SELECT id,name,phone,balance FROM customers WHERE user_id=$1 ORDER BY created_at DESC',[req.user.id]);res.json(r.rows)}catch(e){next(e)}});
app.post('/api/customers',auth,async(req,res,next)=>{try{const id=randomUUID();const r=await q('INSERT INTO customers(id,user_id,name,phone) VALUES($1,$2,$3,$4) RETURNING id,name,phone,balance',[id,req.user.id,String(req.body.name||'').trim(),req.body.phone||null]);await audit(req.user.id,'customer_create',{id});res.status(201).json(r.rows[0])}catch(e){next(e)}});
app.post('/api/sales',auth,async(req,res,next)=>{const client=await pool.connect();try{await client.query('BEGIN');const b=req.body;const customerId=b.customerId||null;const items=Array.isArray(b.items)?b.items:[];if(!items.length)throw new Error('NO_ITEMS');let total=0;for(const item of items){const r=await client.query('SELECT * FROM products WHERE id=$1 AND user_id=$2 FOR UPDATE',[item.productId,req.user.id]);if(!r.rowCount)throw new Error('PRODUCT_NOT_FOUND');const p=r.rows[0];const qty=Number(item.qty);if(!(qty>0)||Number(p.stock_qty)<qty)throw new Error('INSUFFICIENT_STOCK');const price=Number(item.price??p.sale_price);total+=price*qty;await client.query('UPDATE products SET stock_qty=stock_qty-$1 WHERE id=$2',[qty,p.id])}if(Number(b.total)>0&&Math.abs(Number(b.total)-total)<0.01)total=Number(b.total);const id=randomUUID();await client.query('INSERT INTO sales(id,user_id,shop_id,customer_id,total,payment_method,items) VALUES($1,$2,$3,$4,$5,$6,$7)',[id,req.user.id,b.shop||null,customerId,total,String(b.paymentMethod||'cash'),JSON.stringify(items)]);if(String(b.paymentMethod)==='debt'&&customerId)await client.query('UPDATE customers SET balance=balance+$1 WHERE id=$2 AND user_id=$3',[total,customerId,req.user.id]);await client.query('COMMIT');await audit(req.user.id,'sale_create',{id,total});res.status(201).json({id,total})}catch(e){await client.query('ROLLBACK');next(e)}finally{client.release()}});
app.get('/api/dashboard',auth,async(req,res,next)=>{try{const r=await q(`SELECT COALESCE(SUM(total) FILTER(WHERE created_at>=date_trunc('day',now())),0) income,COALESCE((SELECT SUM((value->>'amount')::numeric) FROM jsonb_array_elements(COALESCE(u.state->'entries','[]'::jsonb)) value WHERE (value->>'type')='expense'),0) expense,COALESCE((SELECT SUM(balance) FROM customers WHERE user_id=$1),0) debt FROM users u WHERE u.id=$1 GROUP BY u.id`,[req.user.id]);const x=r.rows[0]||{income:0,expense:0,debt:0};res.json({income:Number(x.income),expense:Number(x.expense),profit:Number(x.income)-Number(x.expense),debt:Number(x.debt)})}catch(e){next(e)}});
app.get('/api/business-health',auth,async(req,res,next)=>{try{const p=await q('SELECT COUNT(*) FILTER(WHERE stock_qty<=min_stock) low,COUNT(*) total FROM products WHERE user_id=$1',[req.user.id]);const c=await q('SELECT COALESCE(SUM(balance),0) debt FROM customers WHERE user_id=$1',[req.user.id]);const signals=[];if(Number(p.rows[0].low)>0)signals.push({level:'warn',text:`${p.rows[0].low} ta mahsulotning qoldig‘i kam.`});else signals.push({level:'good',text:'Ombor qoldig‘i nazoratda.'});if(Number(c.rows[0].debt)>0)signals.push({level:'warn',text:`Jami qarzdorlik: ${Number(c.rows[0].debt).toLocaleString('uz-UZ')} so‘m.`});else signals.push({level:'good',text:'Ochiq qarzdorlik yo‘q.'});res.json({signals})}catch(e){next(e)}});
app.post('/api/payments/proof',auth,upload.single('image'),async(req,res,next)=>{try{if(!req.file)return res.status(400).json({error:'IMAGE_REQUIRED'});res.json({key:req.file.filename})}catch(e){next(e)}});
app.post('/api/payments/request',auth,async(req,res,next)=>{try{const id=randomUUID();await q('INSERT INTO payment_requests(id,user_id,plan,amount,proof_key) VALUES($1,$2,$3,$4,$5)',[id,req.user.id,String(req.body.plan||'monthly'),Number(req.body.amount)||0,req.body.proofKey||null]);await audit(req.user.id,'payment_request',{id});res.status(201).json({id,status:'pending'})}catch(e){next(e)}});
app.get('/api/admin/payments',auth,async(req,res,next)=>{try{if(req.user.role!=='admin')return res.status(403).json({error:'FORBIDDEN'});const r=await q(`SELECT p.*,u.username FROM payment_requests p JOIN users u ON u.id=p.user_id WHERE p.status='pending' ORDER BY p.created_at DESC`);res.json(r.rows)}catch(e){next(e)}});
app.post('/api/admin/payments/:id/approve',auth,async(req,res,next)=>{try{if(req.user.role!=='admin')return res.status(403).json({error:'FORBIDDEN'});const r=await q('SELECT * FROM payment_requests WHERE id=$1 AND status=\'pending\' FOR UPDATE',[req.params.id]);if(!r.rowCount)return res.status(404).json({error:'NOT_FOUND'});await q('UPDATE payment_requests SET status=\'approved\',reviewed_by=$1,reviewed_at=now() WHERE id=$2',[req.user.id,req.params.id]);await q(`UPDATE users SET subscription_until=GREATEST(subscription_until,now())+($1 || ' days')::interval,plan=$2 WHERE id=$3`,[Number(process.env.SUBSCRIPTION_DAYS||30),r.rows[0].plan,r.rows[0].user_id]);await audit(req.user.id,'payment_approve',{paymentId:req.params.id});res.json({ok:true})}catch(e){next(e)}});
app.get('/api/admin/audit',auth,async(req,res,next)=>{try{if(req.user.role!=='admin')return res.status(403).json({error:'FORBIDDEN'});const r=await q('SELECT a.*,u.username FROM audit_logs a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.created_at DESC LIMIT 200');res.json(r.rows)}catch(e){next(e)}});
app.use('/uploads',auth,(req,res,next)=>{res.sendFile(path.join(uploadDir,path.basename(req.path)),{dotfiles:'deny'},next)});
app.use((err,req,res,_next)=>{console.error(err);res.status(err.status||500).json({error:err.message||'SERVER_ERROR'})});
const port=Number(process.env.PORT||3000);app.listen(port,()=>console.log(`Daftar running on http://localhost:${port}`));
